[package]
name = "neatrs"
version = "0.1.0"
edition = "2021"
authors = ["Harry Clough"]
license = "MIT"
readme = "readme.md"
repository = "https://github.com/harryclough/neat-rs"
description = "An implementation of the NEAT algorithm for Rust"

[dependencies]

